// Generated by embed-aba-layout.mjs. Edit the source files under platform/assets/.
export const LAYOUT_CSS = `/*
 * Sistema ABA — interface clínica responsiva v45
 * Camada visual apenas: não altera consultas, autenticação ou registros.
 */

:root {
  --aba-ui-sidebar: 252px;
  --aba-ui-space: clamp(16px, 2vw, 28px);
  --aba-ui-radius: 12px;
  --aba-ui-radius-sm: 9px;
  --aba-ui-shadow: 0 8px 28px rgba(15, 42, 90, .055);
  --aba-ui-shadow-raised: 0 18px 54px rgba(15, 42, 90, .16);
  --aba-ui-focus: 0 0 0 3px rgba(36, 75, 130, .22);
}

html {
  background: var(--aba-bg, #f4f6f9);
  color-scheme: light;
  font-size: 16px;
}

body,
.role-page {
  min-width: 320px;
  overflow-x: hidden;
  -webkit-font-smoothing: antialiased;
  text-rendering: optimizeLegibility;
}

button,
input,
select,
textarea {
  font-family: inherit;
}

button,
a,
select,
input,
textarea {
  -webkit-tap-highlight-color: transparent;
}

button:focus-visible,
a:focus-visible,
select:focus-visible,
input:focus-visible,
textarea:focus-visible {
  outline: 0 !important;
  box-shadow: var(--aba-ui-focus) !important;
}

/* Main clinical workspace */
.aba-shell {
  grid-template-columns: var(--aba-ui-sidebar) minmax(0, 1fr) !important;
  align-items: start;
}

.aba-sidebar {
  width: var(--aba-ui-sidebar);
  padding: 18px 14px 16px !important;
  scrollbar-width: thin;
  scrollbar-color: #b8c5d5 transparent;
}

.aba-brand {
  padding-inline: 4px !important;
}

.aba-userbox {
  padding: 11px 12px !important;
  margin-bottom: 12px !important;
  border-radius: var(--aba-ui-radius-sm) !important;
}

.aba-userbox b {
  font-size: .8125rem !important;
  line-height: 1.35;
}

.aba-userbox span {
  font-size: .75rem !important;
  line-height: 1.4;
}

.aba-nav {
  gap: 3px !important;
}

.aba-nav button {
  min-height: 40px;
  padding: 9px 11px !important;
  border-radius: 7px !important;
  font-size: .8125rem !important;
  line-height: 1.25;
}

.aba-sidebar-bottom {
  gap: 7px !important;
}

.aba-sidebar-bottom .aba-btn {
  min-height: 40px;
  font-size: .75rem !important;
}

.aba-main {
  width: 100%;
  min-height: 100vh;
  padding: var(--aba-ui-space) !important;
}

.aba-topbar {
  position: sticky;
  top: 12px;
  z-index: 100;
  align-items: center !important;
  padding: 17px 19px !important;
  margin-bottom: 16px !important;
  border: 1px solid rgba(214, 221, 232, .96) !important;
  border-top: 3px solid var(--aba-navy, #0f2a5a) !important;
  border-radius: var(--aba-ui-radius) !important;
  background: rgba(255, 255, 255, .96) !important;
  box-shadow: var(--aba-ui-shadow) !important;
  -webkit-backdrop-filter: blur(14px);
  backdrop-filter: blur(14px);
}

.aba-product-kicker {
  margin: 0 0 4px !important;
  font-size: .6875rem !important;
  letter-spacing: .11em !important;
}

.aba-topbar h2 {
  margin: 0 !important;
  font-size: clamp(1.25rem, 2vw, 1.55rem) !important;
  line-height: 1.16;
}

.aba-topbar p {
  margin: 5px 0 0 !important;
  font-size: .8125rem !important;
  line-height: 1.4;
}

.aba-top-actions {
  align-items: center !important;
  justify-content: flex-end;
  gap: 8px !important;
}

#abaActiveClient {
  display: block;
  width: min(260px, 32vw);
  min-width: 210px !important;
  height: 44px;
  padding: 0 38px 0 12px !important;
  border: 1px solid #c8d1dd !important;
  border-radius: 8px !important;
  background-color: #fff;
  color: var(--aba-ink, #172033);
  font-size: .9375rem;
}

#abaRefresh {
  min-height: 44px;
  padding-inline: 15px;
  white-space: nowrap;
}

.aba-admin-tools {
  display: flex;
  align-items: center;
  gap: 8px;
}

.aba-admin-tools .aba-btn {
  min-height: 44px;
  white-space: nowrap;
}

/* Cards and information density */
.aba-view {
  min-width: 0;
}

.aba-view > .aba-grid {
  margin-bottom: 12px;
}

.aba-grid {
  gap: 12px !important;
}

.aba-grid > .aba-card {
  min-width: 0;
  margin-bottom: 0 !important;
}

.aba-card {
  padding: 17px !important;
  margin-bottom: 12px !important;
  border-radius: var(--aba-ui-radius) !important;
  box-shadow: var(--aba-ui-shadow) !important;
}

.aba-card h3 {
  font-size: 1.0625rem !important;
  line-height: 1.25;
}

.aba-card h4 {
  font-size: .9375rem !important;
  line-height: 1.3;
}

.aba-card p,
.aba-list-item p,
.aba-program p,
.aba-alert {
  font-size: .875rem !important;
  line-height: 1.55 !important;
}

.aba-section-head {
  align-items: center !important;
  margin-bottom: 13px !important;
}

.aba-section-head p {
  margin: 4px 0 0 !important;
}

.aba-stat {
  display: flex;
  min-height: 108px;
  flex-direction: column;
  justify-content: space-between;
  border-top: 3px solid #dbe5f0 !important;
}

.aba-stat span {
  font-size: .6875rem !important;
  line-height: 1.3;
  letter-spacing: .055em !important;
}

.aba-stat strong {
  margin-top: 12px !important;
  font-size: 2rem !important;
  line-height: 1;
  font-variant-numeric: tabular-nums;
}

.aba-list {
  gap: 8px !important;
}

.aba-list-item,
.aba-program,
.aba-protocol,
.aba-session-program,
.aba-indicator-card {
  border-radius: var(--aba-ui-radius-sm) !important;
}

.aba-list-item {
  padding: 11px 12px !important;
}

.aba-list-item strong {
  font-size: .875rem !important;
  line-height: 1.35;
}

.aba-list-item small,
.aba-history,
.aba-score-guide {
  font-size: .8125rem !important;
  line-height: 1.45;
}

.aba-badge {
  max-width: 100%;
  padding: 4px 8px !important;
  font-size: .75rem !important;
  line-height: 1.25;
  overflow-wrap: anywhere;
}

.aba-btn {
  min-height: 42px !important;
  padding: 9px 13px !important;
  border-radius: 8px !important;
  font-size: .875rem !important;
  line-height: 1.2;
}

.aba-btn.small {
  min-height: 38px !important;
  padding: 8px 11px !important;
  font-size: .8125rem !important;
}

.aba-field label {
  font-size: .8125rem !important;
  line-height: 1.35;
  letter-spacing: .035em !important;
}

.aba-field input,
.aba-field select,
.aba-field textarea {
  min-height: 44px !important;
  padding: 10px 12px !important;
  border-radius: 8px !important;
  font-size: .9375rem;
}

.aba-field textarea {
  min-height: 104px !important;
}

.aba-empty {
  padding: 26px 18px !important;
  border-radius: var(--aba-ui-radius-sm) !important;
  font-size: .8125rem !important;
  line-height: 1.5;
}

.aba-empty b,
.aba-empty span {
  display: block;
}

.aba-empty span {
  margin-top: 4px;
}

/* Dashboard priorities */
.aba-production-priority {
  padding: 17px !important;
  margin-bottom: 12px !important;
  border: 1px solid var(--aba-line, #d6dde8) !important;
  border-top: 3px solid var(--aba-navy, #0f2a5a) !important;
  border-radius: var(--aba-ui-radius) !important;
  box-shadow: var(--aba-ui-shadow) !important;
}

.aba-priority-head h3 {
  margin-top: 4px !important;
  font-size: 1.125rem !important;
  line-height: 1.2;
}

.aba-priority-head > div > span {
  font-size: .6875rem !important;
  letter-spacing: .095em !important;
}

.aba-priority-grid {
  gap: 9px !important;
  margin-top: 14px !important;
}

.aba-priority-grid > div {
  display: flex;
  min-height: 78px;
  flex-direction: column;
  justify-content: space-between;
  padding: 11px 12px !important;
  border: 1px solid #e5eaf1;
  border-radius: 9px !important;
  background: #f7f9fc !important;
}

.aba-priority-grid span {
  font-size: .75rem !important;
  line-height: 1.3;
}

.aba-priority-grid strong {
  margin-top: 8px !important;
  font-size: 1.7rem !important;
  line-height: 1;
}

/* Data tables and operational lists */
.aba-table-wrap {
  max-width: 100%;
  border-radius: var(--aba-ui-radius-sm) !important;
  overscroll-behavior-inline: contain;
  scrollbar-width: thin;
}

.aba-table th,
.aba-table td {
  padding: 11px 12px !important;
}

.aba-table th {
  font-size: .8125rem !important;
  line-height: 1.35;
}

.aba-table td {
  font-size: .875rem !important;
  line-height: 1.45;
}

.aba-table tbody tr:nth-child(even) {
  background: #fbfcfe;
}

.aba-toolbar {
  gap: 9px !important;
}

.aba-agenda-toolbar {
  gap: 11px !important;
}

.aba-agenda-item {
  min-width: 0;
  padding: 12px 14px !important;
  border-radius: var(--aba-ui-radius-sm) !important;
}

.aba-agenda-item time {
  font-size: .875rem;
}

.aba-agenda-item b {
  font-size: .875rem !important;
}

.aba-agenda-item span,
.aba-agenda-item small {
  font-size: .75rem !important;
  line-height: 1.4;
}

.aba-clinical-chart {
  max-height: 230px !important;
}

/* Dialogs */
.aba-modal,
.aba-production-modal,
.aba-credential-modal,
.role-modal {
  padding: max(12px, env(safe-area-inset-top)) 12px max(12px, env(safe-area-inset-bottom)) !important;
}

.aba-modal-box,
.aba-production-dialog,
.aba-credential-box,
.role-modal-box {
  border-radius: 14px !important;
  box-shadow: var(--aba-ui-shadow-raised) !important;
}

.aba-production-dialog-head,
.aba-production-dialog-actions {
  padding-inline: 18px !important;
}

.aba-flash,
.role-flash {
  right: 14px !important;
  bottom: max(14px, env(safe-area-inset-bottom)) !important;
  left: auto;
  max-width: min(420px, calc(100vw - 28px));
  border-radius: 10px !important;
}

/* Admin actions belong to the header, never over clinical content. */
.aba-credential-fab,
.aba-parent-fab {
  display: none !important;
}

/* Mobile navigation elements are created by the responsive shell. */
.aba-mobile-menu,
.role-mobile-menu {
  display: none;
}

.aba-nav-backdrop,
.role-nav-backdrop {
  position: fixed;
  inset: 0;
  z-index: 1190;
  display: block;
  border: 0;
  background: rgba(8, 26, 59, .44);
  opacity: 0;
  pointer-events: none;
  transition: opacity .2s ease;
  -webkit-backdrop-filter: blur(2px);
  backdrop-filter: blur(2px);
}

/* Family and applicator portals */
.role-shell {
  grid-template-columns: var(--aba-ui-sidebar) minmax(0, 1fr) !important;
  align-items: start;
}

.role-side {
  position: sticky;
  top: 0;
  width: var(--aba-ui-sidebar);
  height: 100dvh;
  padding: 18px 14px !important;
  overflow-y: auto;
}

.role-nav {
  gap: 4px !important;
}

.role-nav button {
  min-height: 42px;
  padding: 9px 11px !important;
  border-radius: 7px !important;
  font-size: .875rem;
}

.role-main {
  min-height: 100vh;
  padding: var(--aba-ui-space) !important;
}

.role-top {
  top: 12px !important;
  padding: 17px 19px !important;
  border-radius: var(--aba-ui-radius) !important;
  background: rgba(255, 255, 255, .96) !important;
  box-shadow: var(--aba-ui-shadow) !important;
  -webkit-backdrop-filter: blur(14px);
  backdrop-filter: blur(14px);
}

.role-top h1 {
  font-family: Inter, ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif !important;
  font-size: clamp(1.25rem, 2vw, 1.55rem) !important;
  line-height: 1.2;
  letter-spacing: -.018em;
}

.role-top p,
.role-card p,
.role-list-item p,
.role-program p {
  font-size: .9375rem !important;
  line-height: 1.55 !important;
}

.role-content {
  gap: 12px !important;
  margin-top: 14px !important;
}

.role-card {
  padding: 17px !important;
  border-radius: var(--aba-ui-radius) !important;
  box-shadow: var(--aba-ui-shadow) !important;
}

.role-card h2,
.role-card h3 {
  font-family: Inter, ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif !important;
  letter-spacing: -.018em;
}

.role-stat {
  display: flex;
  min-height: 102px;
  flex-direction: column;
  justify-content: space-between;
  border-top: 3px solid #dbe5f0 !important;
}

.role-stat span,
.role-label {
  font-size: .8125rem !important;
  line-height: 1.35;
}

.role-stat strong {
  font-size: 1.9rem !important;
  line-height: 1;
}

.role-btn {
  min-height: 42px;
  padding: 9px 13px !important;
  border-radius: 8px !important;
  font-size: .875rem;
}

.role-btn.small {
  min-height: 38px;
  padding: 8px 11px !important;
  font-size: .8125rem !important;
}

.role-select,
.role-input,
.role-textarea {
  min-height: 44px;
  padding: 10px 12px !important;
  border-radius: 8px !important;
  font-size: .9375rem;
}

.role-table th,
.role-table td {
  padding: 11px 12px !important;
  font-size: .875rem;
  line-height: 1.45;
}

.role-table th {
  font-size: .8125rem;
}

/* Login */
.aba-login-page {
  min-height: 100dvh !important;
  padding: clamp(16px, 4vw, 36px) !important;
}

.aba-login-card {
  width: min(470px, 100%) !important;
  padding: clamp(22px, 5vw, 34px) !important;
  border-radius: 16px !important;
  box-shadow: 0 22px 64px rgba(15, 42, 90, .13) !important;
}

.aba-login-card > h2 {
  margin: 16px 0 8px;
  font-size: 1.6rem;
  line-height: 1.2;
}

.aba-login-intro,
.aba-login-note {
  font-size: .8125rem !important;
  line-height: 1.55 !important;
}

.aba-login-actions .aba-btn {
  min-height: 42px !important;
}

@media (max-width: 1180px) {
  .aba-grid.cols-5 {
    grid-template-columns: repeat(3, minmax(0, 1fr)) !important;
  }

  .aba-top-actions {
    max-width: 58%;
  }

  .aba-admin-tools {
    width: 100%;
    justify-content: flex-end;
  }
}

@media (max-width: 900px) {
  body.aba-nav-open,
  body.role-nav-open {
    overflow: hidden;
  }

  .aba-shell,
  .role-shell {
    display: block !important;
  }

  .aba-main,
  .role-main {
    width: 100% !important;
    min-height: 100dvh;
    margin: 0 !important;
    padding: 14px !important;
  }

  .aba-sidebar,
  .role-side {
    position: fixed !important;
    inset: 0 auto 0 0 !important;
    z-index: 1200 !important;
    display: flex !important;
    width: min(88vw, 330px) !important;
    height: 100dvh !important;
    padding: max(18px, env(safe-area-inset-top)) 14px max(18px, env(safe-area-inset-bottom)) !important;
    overflow-y: auto;
    transform: translateX(-104%);
    transition: transform .2s ease !important;
    box-shadow: 22px 0 60px rgba(8, 26, 59, .18) !important;
  }

  .aba-sidebar.mobile-open,
  .role-side.mobile-open {
    transform: translateX(0) !important;
  }

  body.aba-nav-open .aba-nav-backdrop,
  body.role-nav-open .role-nav-backdrop {
    opacity: 1;
    pointer-events: auto;
  }

  .aba-nav,
  .role-nav {
    display: grid !important;
    grid-template-columns: 1fr !important;
  }

  .aba-nav button,
  .role-nav button {
    min-height: 44px;
    font-size: .875rem !important;
  }

  .aba-sidebar-bottom,
  .role-side-bottom {
    margin-top: auto !important;
  }

  .aba-topbar,
  .role-top {
    position: sticky !important;
    top: 0 !important;
    z-index: 100 !important;
    min-height: 72px;
    padding-right: 94px !important;
  }

  .aba-mobile-menu,
  .role-mobile-menu {
    position: absolute !important;
    top: 13px !important;
    right: 13px !important;
    bottom: auto !important;
    left: auto !important;
    z-index: 2 !important;
    display: inline-flex !important;
    min-width: 72px !important;
    min-height: 44px !important;
    align-items: center;
    justify-content: center;
    gap: 7px;
    padding: 0 12px !important;
    border: 1px solid var(--aba-navy, #0f2a5a) !important;
    border-radius: 9px !important;
    background: var(--aba-navy, #0f2a5a) !important;
    color: #fff !important;
    font-size: .8125rem !important;
    font-weight: 800;
    box-shadow: 0 7px 20px rgba(15, 42, 90, .18) !important;
  }

  .role-mobile-menu {
    border-color: var(--wt-navy, #0f2a5a) !important;
    background: var(--wt-navy, #0f2a5a) !important;
  }

  .aba-top-actions {
    max-width: none;
  }

  .aba-grid.cols-3,
  .aba-grid.cols-4,
  .role-grid {
    grid-template-columns: repeat(2, minmax(0, 1fr)) !important;
  }

  .aba-grid.cols-5 {
    grid-template-columns: repeat(3, minmax(0, 1fr)) !important;
  }

  .aba-grid.cols-2,
  .aba-protocol-grid,
  .aba-indicator-grid {
    grid-template-columns: 1fr !important;
  }

  .role-side {
    gap: 13px !important;
    border-right: 1px solid var(--wt-brand-line, #d9e1eb) !important;
    border-bottom: 0 !important;
  }
}

@media (max-width: 620px) {
  .aba-main,
  .role-main {
    padding: 0 10px calc(20px + env(safe-area-inset-bottom)) !important;
  }

  .aba-topbar,
  .role-top {
    width: calc(100% + 20px);
    min-height: 68px;
    margin: 0 -10px 12px !important;
    padding: 13px 92px 12px 12px !important;
    border-top-width: 0 !important;
    border-right: 0 !important;
    border-left: 0 !important;
    border-radius: 0 0 13px 13px !important;
  }

  .aba-product-kicker,
  .aba-topbar p {
    display: none !important;
  }

  .aba-topbar h2,
  .role-top h1 {
    min-height: 28px;
    display: flex;
    align-items: center;
    font-size: 1.15rem !important;
  }

  .aba-mobile-menu,
  .role-mobile-menu {
    top: 12px !important;
    right: 12px !important;
  }

  .aba-top-actions {
    display: grid !important;
    grid-template-columns: minmax(0, 1fr) auto;
    gap: 8px !important;
    width: calc(100vw - 24px);
    margin-top: 11px !important;
  }

  #abaActiveClient {
    width: 100% !important;
    min-width: 0 !important;
    height: 46px;
    font-size: 1rem;
  }

  #abaRefresh {
    min-width: 96px;
    min-height: 46px !important;
  }

  .aba-admin-tools {
    grid-column: 1 / -1;
    display: grid;
    grid-template-columns: 1fr;
    width: 100%;
  }

  .aba-admin-tools .aba-btn {
    width: 100%;
    min-width: 0;
    white-space: normal;
  }

  .aba-card,
  .role-card {
    padding: 14px !important;
    margin-bottom: 10px !important;
    border-radius: 11px !important;
  }

  .aba-view > .aba-grid {
    margin-bottom: 10px;
  }

  .aba-grid {
    gap: 9px !important;
  }

  .aba-view#abaView-dashboard > .aba-grid.cols-5,
  .role-grid {
    grid-template-columns: repeat(2, minmax(0, 1fr)) !important;
  }

  .aba-view#abaView-dashboard > .aba-grid.cols-5 > :last-child:nth-child(odd),
  .role-grid > :last-child:nth-child(odd) {
    grid-column: 1 / -1;
  }

  .aba-grid.cols-2,
  .aba-grid.cols-3,
  .aba-grid.cols-4,
  .aba-protocol-grid,
  .aba-indicator-grid {
    grid-template-columns: 1fr !important;
  }

  .aba-stat,
  .role-stat {
    min-height: 88px;
    padding: 12px !important;
  }

  .aba-stat span,
  .role-stat span {
    font-size: .75rem !important;
  }

  .aba-stat strong,
  .role-stat strong {
    margin-top: 10px !important;
    font-size: 1.75rem !important;
  }

  .aba-production-priority {
    padding: 14px !important;
    margin-bottom: 10px !important;
    border-radius: 11px !important;
  }

  .aba-priority-head {
    align-items: center !important;
    gap: 10px !important;
  }

  .aba-priority-head h3 {
    max-width: 230px;
    font-size: 1.08rem !important;
  }

  .aba-priority-head .aba-btn {
    flex: 0 0 auto;
    min-height: 42px !important;
  }

  .aba-priority-grid {
    grid-template-columns: repeat(2, minmax(0, 1fr)) !important;
    gap: 8px !important;
    margin-top: 12px !important;
  }

  .aba-priority-grid > div {
    min-height: 72px;
    padding: 10px !important;
  }

  .aba-priority-grid strong {
    font-size: 1.55rem !important;
  }

  .aba-section-head {
    align-items: flex-start !important;
    gap: 10px !important;
  }

  .aba-section-head > .aba-top-actions {
    width: 100%;
  }

  .aba-program-head,
  .aba-indicator-card header,
  .aba-list-item header {
    gap: 8px !important;
  }

  .aba-program .facts,
  .aba-indicator-facts,
  .aba-form-grid,
  .aba-compare-box,
  .role-facts {
    grid-template-columns: 1fr !important;
  }

  .aba-table {
    min-width: 700px;
  }

  .aba-table th,
  .aba-table td,
  .role-table th,
  .role-table td {
    padding: 10px !important;
    font-size: .8125rem !important;
  }

  .aba-agenda-toolbar {
    grid-template-columns: 1fr !important;
  }

  .aba-agenda-item {
    grid-template-columns: 1fr !important;
    gap: 8px !important;
  }

  .aba-row-actions,
  .aba-protocol-actions,
  .role-trials {
    width: 100%;
  }

  .aba-row-actions .aba-btn,
  .aba-protocol-actions .aba-btn {
    flex: 1 1 auto;
  }

  .aba-production-dialog,
  .aba-modal-box,
  .aba-credential-box,
  .role-modal-box {
    width: 100% !important;
    max-height: calc(100dvh - 20px) !important;
    border-radius: 13px !important;
  }

  .aba-production-dialog #abaProductionBody,
  .aba-modal-box,
  .aba-credential-box,
  .role-modal-box {
    padding: 14px !important;
  }

  .aba-production-dialog-actions,
  .aba-modal-actions,
  .aba-credential-actions,
  .role-modal-actions {
    display: grid !important;
    grid-template-columns: 1fr 1fr;
    gap: 8px !important;
  }

  .aba-production-dialog-actions .aba-btn,
  .aba-modal-actions .aba-btn,
  .aba-credential-actions button,
  .role-modal-actions .role-btn {
    width: 100%;
  }

  .aba-flash,
  .role-flash {
    right: 10px !important;
    left: 10px !important;
    bottom: max(10px, env(safe-area-inset-bottom)) !important;
    max-width: none;
  }

  .role-top {
    display: block !important;
  }

  .role-top > div:last-child {
    min-width: 0 !important;
    width: calc(100vw - 24px);
    margin-top: 11px;
  }

  .role-select,
  .role-input,
  .role-textarea,
  .aba-field input,
  .aba-field select,
  .aba-field textarea {
    font-size: 1rem !important;
  }

  .role-chart {
    min-height: 160px !important;
    overflow-x: auto;
  }

  .aba-login-page {
    align-items: flex-start !important;
    padding: 12px !important;
  }

  .aba-login-card {
    margin: max(8px, env(safe-area-inset-top)) auto;
    padding: 22px 18px !important;
    border-radius: 14px !important;
  }

  .aba-login-brand .aba-site-logo {
    width: min(300px, 82vw) !important;
    height: 60px !important;
  }

  .aba-login-actions {
    display: grid !important;
    grid-template-columns: 1fr !important;
  }
}

@media (max-width: 380px) {
  .aba-main,
  .role-main {
    padding-inline: 8px !important;
  }

  .aba-topbar,
  .role-top {
    width: calc(100% + 16px);
    margin-inline: -8px !important;
  }

  .aba-priority-head h3 {
    max-width: 190px;
    font-size: 1rem !important;
  }

  .aba-priority-head .aba-btn {
    padding-inline: 9px !important;
  }

  .aba-admin-tools {
    grid-template-columns: 1fr;
  }
}

@media (prefers-reduced-motion: reduce) {
  .aba-sidebar,
  .role-side,
  .aba-nav-backdrop,
  .role-nav-backdrop {
    transition: none !important;
  }
}

@media print {
  .aba-admin-tools,
  .aba-mobile-menu,
  .role-mobile-menu,
  .aba-nav-backdrop,
  .role-nav-backdrop {
    display: none !important;
  }
}
`;
export const LAYOUT_JS = `const $=(selector,root=document)=>root.querySelector(selector);

function setAdminNavigation(open){
  const side=$('.aba-sidebar'),button=$('#abaMobileMenu');
  side?.classList.toggle('mobile-open',open);
  document.body.classList.toggle('aba-nav-open',open);
  if(button){
    button.setAttribute('aria-expanded',String(open));
    button.setAttribute('aria-label',open?'Fechar navegação clínica':'Abrir navegação clínica');
  }
}

function setRoleNavigation(open){
  const side=$('.role-side'),button=$('#roleMobileMenu');
  side?.classList.toggle('mobile-open',open);
  document.body.classList.toggle('role-nav-open',open);
  if(button){
    button.setAttribute('aria-expanded',String(open));
    button.setAttribute('aria-label',open?'Fechar navegação':'Abrir navegação');
  }
}

function ensureBackdrop(id,className,onClose){
  let backdrop=$('#'+id);
  if(backdrop)return backdrop;
  backdrop=document.createElement('button');
  backdrop.id=id;
  backdrop.type='button';
  backdrop.className=className;
  backdrop.tabIndex=-1;
  backdrop.setAttribute('aria-label','Fechar navegação');
  backdrop.onclick=onClose;
  document.body.appendChild(backdrop);
  return backdrop;
}

function ensureAdminShell(){
  const side=$('.aba-sidebar'),top=$('.aba-topbar'),nav=$('#abaNav'),button=$('#abaMobileMenu');
  if(!side||!top||!nav||!button)return;

  if(button.parentElement!==top)top.appendChild(button);
  if(button.dataset.layoutReady!=='true'){
    button.dataset.layoutReady='true';
    button.innerHTML='<span aria-hidden="true">☰</span><span>Menu</span>';
    button.setAttribute('aria-controls','abaNav');
    button.setAttribute('aria-expanded','false');
    button.setAttribute('aria-label','Abrir navegação clínica');
    button.onclick=()=>setAdminNavigation(!side.classList.contains('mobile-open'));
  }

  ensureBackdrop('abaNavBackdrop','aba-nav-backdrop aba-no-print',()=>setAdminNavigation(false));
  if(nav.dataset.layoutReady!=='true'){
    nav.dataset.layoutReady='true';
    nav.addEventListener('click',()=>{if(innerWidth<=900)setAdminNavigation(false)});
  }
}

function placeAdminTools(){
  const host=$('.aba-top-actions');
  if(!host)return;
  const credential=$('#abaCredentialFab');
  if(!credential)return;

  let group=$('#abaAdminTools');
  if(!group){
    group=document.createElement('div');
    group.id='abaAdminTools';
    group.className='aba-admin-tools aba-no-print';
    group.setAttribute('aria-label','Ações administrativas');
    host.appendChild(group);
  }

  if(credential){
    credential.className='aba-btn secondary small aba-admin-tool';
    credential.setAttribute('aria-label','Alterar minhas credenciais administrativas');
    if(credential.parentElement!==group)group.appendChild(credential);
  }
}

function ensureRoleShell(){
  const side=$('.role-side'),top=$('.role-top'),nav=$('.role-nav');
  if(!side||!top||!nav)return;
  if(!nav.id)nav.id='roleNavigation';

  let button=$('#roleMobileMenu');
  if(!button){
    button=document.createElement('button');
    button.id='roleMobileMenu';
    button.className='role-mobile-menu';
    button.type='button';
    button.innerHTML='<span aria-hidden="true">☰</span><span>Menu</span>';
    button.setAttribute('aria-label','Abrir navegação');
    button.setAttribute('aria-controls',nav.id);
    button.setAttribute('aria-expanded','false');
    button.onclick=()=>setRoleNavigation(!side.classList.contains('mobile-open'));
    top.appendChild(button);
  }

  ensureBackdrop('roleNavBackdrop','role-nav-backdrop',()=>setRoleNavigation(false));
  if(nav.dataset.layoutReady!=='true'){
    nav.dataset.layoutReady='true';
    nav.addEventListener('click',()=>{if(innerWidth<=900)setRoleNavigation(false)});
  }
}

let queued=false;
function patch(){
  queued=false;
  ensureAdminShell();
  placeAdminTools();
  ensureRoleShell();
}
function schedule(){
  if(queued)return;
  queued=true;
  requestAnimationFrame(patch);
}

function boot(){
  patch();
  new MutationObserver(schedule).observe(document.documentElement,{subtree:true,childList:true});
  document.addEventListener('keydown',event=>{
    if(event.key==='Escape'){
      setAdminNavigation(false);
      setRoleNavigation(false);
    }
  });
  window.addEventListener('resize',()=>{
    if(innerWidth>900){
      setAdminNavigation(false);
      setRoleNavigation(false);
    }
  },{passive:true});
}

if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});
else boot();
`;
