import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.57.4";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"GET,POST,OPTIONS","Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store","X-ABA-Version":"20260911-auth-version-v2"};
const reply=(body:any,status=200)=>new Response(JSON.stringify(body),{status,headers:cors});
const safeName=(s:string)=>String(s||"arquivo").normalize("NFKD").replace(/[^a-zA-Z0-9._-]+/g,"-").slice(0,120)||"arquivo";
const matches=(expected:any,jwtVersion:string)=>expected==null||String(expected)===jwtVersion;
Deno.serve(async(req)=>{
 if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors});
 try{
  const url=Deno.env.get("SUPABASE_URL")!,anon=Deno.env.get("SUPABASE_ANON_KEY")!,service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
  const auth=req.headers.get("Authorization")||"",caller=createClient(url,anon,{global:{headers:{Authorization:auth}},auth:{persistSession:false,autoRefreshToken:false}});
  const {data:{user},error:ue}=await caller.auth.getUser();if(ue||!user)return reply({error:"unauthorized"},401);
  const jwtVersion=String(user.app_metadata?.aba_auth_version||"");
  const admin=createClient(url,service,{auth:{persistSession:false,autoRefreshToken:false}});
  const {data:meRaw,error:meErr}=await admin.from("aba_professionals").select("id,full_name,role,active,auth_version").eq("user_id",user.id).eq("active",true).maybeSingle();if(meErr)throw meErr;
  const me=meRaw&&matches(meRaw.auth_version,jwtVersion)?meRaw:null;
  const {data:gRaw,error:gErr}=await admin.from("aba_guardian_access").select("client_id,guardian_name,relationship,active,auth_version").eq("user_id",user.id).eq("active",true);if(gErr)throw gErr;
  const guardianLinks=(gRaw||[]).filter((x:any)=>matches(x.auth_version,jwtVersion));
  if((meRaw&&!me)&&(!gRaw?.length||!guardianLinks.length))return reply({error:"credential_generation_revoked"},401);
  const isPro=!!me&&["admin","supervisor"].includes(me.role),isGuardian=guardianLinks.length>0;
  async function canClient(clientId:string){if(me?.role==="admin")return true;if(me?.role!=="supervisor")return false;const {data:direct}=await admin.from("aba_client_professionals").select("id").eq("client_id",clientId).eq("professional_id",me.id).eq("active",true).limit(1);if(direct?.length)return true;const {data:links}=await admin.from("aba_supervision_links").select("supervisee_id").eq("supervisor_id",me.id).eq("active",true);const ids=(links||[]).map((x:any)=>x.supervisee_id);if(!ids.length)return false;const {data:via}=await admin.from("aba_client_professionals").select("id").eq("client_id",clientId).eq("active",true).in("professional_id",ids).limit(1);return !!via?.length}
  const guardianCan=(clientId:string)=>guardianLinks.some((x:any)=>x.client_id===clientId);
  async function familyData(clientId:string,guardianMode:boolean){if(guardianMode&&!guardianCan(clientId))throw new Error("forbidden");if(!guardianMode&&!(await canClient(clientId)))throw new Error("forbidden");const [{data:plans,error:pe},{data:reports,error:re}]=await Promise.all([admin.from("aba_family_guidance_plans").select("*").eq("client_id",clientId).eq("active",true).order("created_at"),admin.from("aba_family_reports").select("*").eq("client_id",clientId).neq("status","archived").order("report_at",{ascending:false})]);if(pe)throw pe;if(re)throw re;const visiblePlans=guardianMode?(plans||[]).filter((x:any)=>x.visible_to_guardian):(plans||[]),pids=visiblePlans.map((x:any)=>x.id);const {data:items,error:ie}=pids.length?await admin.from("aba_family_guidance_items").select("*").in("plan_id",pids).eq("active",true).order("position"):{data:[],error:null};if(ie)throw ie;const itemIds=(items||[]).map((x:any)=>x.id);let checks:any[]=[];if(itemIds.length){let q=admin.from("aba_family_guidance_checks").select("item_id,check_date,checked,checked_at,note").in("item_id",itemIds).gte("check_date",new Date(Date.now()-30*86400000).toISOString().slice(0,10)).order("check_date",{ascending:false});if(guardianMode)q=q.eq("guardian_user_id",user.id);const {data,error}=await q;if(error)throw error;checks=data||[]}const visibleReports=guardianMode?(reports||[]).filter((x:any)=>x.visible_to_guardian&&["in_review","published"].includes(x.status)):(reports||[]),rids=visibleReports.map((x:any)=>x.id);const {data:files,error:fe}=rids.length?await admin.from("aba_family_report_files").select("id,report_id,file_name,mime_type,storage_path").in("report_id",rids):{data:[],error:null};if(fe)throw fe;const signed:any[]=[];for(const f of files||[]){const {data:s}=await admin.storage.from("aba-family-reports").createSignedUrl(f.storage_path,3600);signed.push({...f,url:s?.signedUrl||null,storage_path:undefined})}return {plans:visiblePlans.map((p:any)=>({...p,items:(items||[]).filter((i:any)=>i.plan_id===p.id).map((i:any)=>({...i,checks:checks.filter((c:any)=>c.item_id===i.id)}))})),reports:visibleReports.map((r:any)=>({...r,files:signed.filter((f:any)=>f.report_id===r.id)}))}}
  if(req.method==="GET"){const u=new URL(req.url),clientId=u.searchParams.get("client_id")||"";if(!clientId)return reply({error:"client_id_required"},400);const guardianMode=!isPro&&isGuardian;if(!isPro&&!guardianMode)return reply({error:"forbidden"},403);return reply({ok:true,role:guardianMode?"guardian":me?.role,data:await familyData(clientId,guardianMode)})}
  if(req.method!=="POST")return reply({error:"method_not_allowed"},405);
  const ct=req.headers.get("content-type")||"";
  if(ct.includes("multipart/form-data")){if(!isPro)return reply({error:"forbidden"},403);const fd=await req.formData();if(String(fd.get("action")||"")!=="upload_report_file")return reply({error:"bad_action"},400);const clientId=String(fd.get("client_id")||""),reportId=String(fd.get("report_id")||"");if(!(await canClient(clientId)))return reply({error:"forbidden"},403);const file=fd.get("file");if(!(file instanceof File))return reply({error:"file_required"},400);if(file.size>10485760)return reply({error:"file_too_large"},400);const {data:report}=await admin.from("aba_family_reports").select("id").eq("id",reportId).eq("client_id",clientId).maybeSingle();if(!report)return reply({error:"report_not_found"},404);const path=`${clientId}/${reportId}/${crypto.randomUUID()}-${safeName(file.name)}`;const {error:up}=await admin.storage.from("aba-family-reports").upload(path,file,{contentType:file.type||"application/octet-stream",upsert:false});if(up)throw up;const {data:row,error:ri}=await admin.from("aba_family_report_files").insert({report_id:reportId,client_id:clientId,storage_path:path,file_name:file.name,mime_type:file.type||null}).select().single();if(ri)throw ri;return reply({ok:true,file:row})}
  const body=await req.json(),action=String(body.action||"");
  if(action==="toggle_check"){if(!isGuardian)return reply({error:"forbidden"},403);const clientId=String(body.client_id||""),itemId=String(body.item_id||"");if(!guardianCan(clientId))return reply({error:"forbidden"},403);const {data:item}=await admin.from("aba_family_guidance_items").select("id,plan_id,client_id").eq("id",itemId).eq("client_id",clientId).eq("active",true).maybeSingle();if(!item)return reply({error:"item_not_found"},404);const checked=!!body.checked,today=new Date().toISOString().slice(0,10);const {error}=await admin.from("aba_family_guidance_checks").upsert({item_id:item.id,plan_id:item.plan_id,client_id:clientId,guardian_user_id:user.id,check_date:today,checked,checked_at:checked?new Date().toISOString():null,note:body.note||null,updated_at:new Date().toISOString()},{onConflict:"item_id,guardian_user_id,check_date"});if(error)throw error;return reply({ok:true})}
  if(!isPro)return reply({error:"forbidden"},403);const clientId=String(body.client_id||"");if(!(await canClient(clientId)))return reply({error:"forbidden"},403);
  if(action==="save_plan"){const payload={client_id:clientId,supervisor_id:me!.id,title:String(body.title||"Plano de orientação familiar"),objective:String(body.objective||"")||null,active:true,visible_to_guardian:body.visible_to_guardian!==false,updated_at:new Date().toISOString()};let plan:any;if(body.plan_id){const {data,error}=await admin.from("aba_family_guidance_plans").update(payload).eq("id",body.plan_id).eq("client_id",clientId).select().single();if(error)throw error;plan=data}else{const {data,error}=await admin.from("aba_family_guidance_plans").insert(payload).select().single();if(error)throw error;plan=data}const items=Array.isArray(body.items)?body.items:[];if(items.length){await admin.from("aba_family_guidance_items").update({active:false,updated_at:new Date().toISOString()}).eq("plan_id",plan.id);for(let i=0;i<items.length;i++){const x=items[i];if(!String(x.label||"").trim())continue;const row={plan_id:plan.id,client_id:clientId,label:String(x.label).trim(),position:i+1,active:true,updated_at:new Date().toISOString()};if(x.id)await admin.from("aba_family_guidance_items").update(row).eq("id",x.id).eq("plan_id",plan.id);else await admin.from("aba_family_guidance_items").insert(row)}}return reply({ok:true,plan})}
  if(action==="save_report"){const payload={client_id:clientId,supervisor_id:me!.id,title:String(body.title||"Relatório de acompanhamento"),report_type:String(body.report_type||"orientacao_familiar"),status:["draft","in_review","published"].includes(body.status)?body.status:"in_review",content_text:String(body.content_text||"")||null,report_at:body.report_at||new Date().toISOString(),visible_to_guardian:body.visible_to_guardian!==false,next_reevaluation_label:String(body.next_reevaluation_label||"")||null,updated_at:new Date().toISOString()};let report:any;if(body.report_id){const {data,error}=await admin.from("aba_family_reports").update(payload).eq("id",body.report_id).eq("client_id",clientId).select().single();if(error)throw error;report=data}else{const {data,error}=await admin.from("aba_family_reports").insert(payload).select().single();if(error)throw error;report=data}return reply({ok:true,report})}
  return reply({error:"bad_action"},400);
 }catch(e){console.error("aba_family_plan_error",e);const m=String((e as any)?.message||e);return reply({error:m==="forbidden"?"forbidden":m},m==="forbidden"?403:500)}
});
