import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.57.4";

const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store","X-ABA-Version":"20260911-parent-auth-version-v6"};
const reply=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:cors});
const pct=(a:number,b:number)=>(b?Math.round((a/b)*1000)/10:0);
const asNumber=(value:unknown)=>{const n=Number(value);return Number.isFinite(n)?n:null};
const dayKey=(value:string|Date)=>new Intl.DateTimeFormat("en-CA",{timeZone:"America/Sao_Paulo"}).format(new Date(value));
const durationMinutes=(start:string,end:string|null)=>{if(!start||!end)return null;const m=Math.round((new Date(end).getTime()-new Date(start).getTime())/60000);return Number.isFinite(m)&&m>=0?m:null};
async function byClient(clientIds:string[],load:(clientId:string)=>PromiseLike<{data:any[]|null;error:any}>){const responses=await Promise.all(clientIds.map(load));const failed=responses.find(r=>r.error);return {data:failed?null:responses.flatMap(r=>r.data||[]),error:failed?.error||null}}
function indicatorValue(indicator:any,record:any){if(!record)return null;if(record.successes!=null&&record.opportunities)return {value:pct(Number(record.successes),Number(record.opportunities)),unit:"%",detail:`${record.successes}/${record.opportunities}`};for(const [raw,unit] of [[record.frequency_count,indicator?.unit||"ocorrências"],[record.duration_seconds,indicator?.unit||"s"],[record.latency_seconds,indicator?.unit||"s"],[record.value_numeric,indicator?.unit||""]] as Array<[unknown,string]>){const value=asNumber(raw);if(value!=null)return {value,unit,detail:null}}if(record.value_text)return {value:record.value_text,unit:indicator?.unit||"",detail:null};return null}
function behaviorMeasure(record:any){const parts:string[]=[];if(record.frequency!=null)parts.push(`frequência ${record.frequency}`);if(record.duration_seconds!=null)parts.push(`duração ${record.duration_seconds}s`);if(record.latency_seconds!=null)parts.push(`latência ${record.latency_seconds}s`);if(record.intensity)parts.push(`intensidade ${record.intensity}`);return parts.join(" · ")||"registro descritivo"}
const authMatches=(expected:any,jwtVersion:string)=>expected==null||String(expected)===jwtVersion;

Deno.serve(async(req)=>{
 if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors});
 if(req.method!=="GET")return reply({error:"method_not_allowed"},405);
 try{
  const url=Deno.env.get("SUPABASE_URL")!,anon=Deno.env.get("SUPABASE_ANON_KEY")!,service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,auth=req.headers.get("Authorization")||"";
  const caller=createClient(url,anon,{global:{headers:{Authorization:auth}},auth:{persistSession:false,autoRefreshToken:false}});
  const {data:{user},error:userError}=await caller.auth.getUser();if(userError||!user)return reply({error:"unauthorized"},401);
  const jwtVersion=String(user.app_metadata?.aba_auth_version||"");
  const admin=createClient(url,service,{auth:{persistSession:false,autoRefreshToken:false}});
  const {data:rawLinks,error:linksError}=await admin.from("aba_guardian_access").select("client_id,guardian_name,guardian_email,relationship,can_view_assessments,can_view_sessions,can_view_programs,auth_version").eq("user_id",user.id).eq("active",true);
  if(linksError)throw linksError;
  const links=(rawLinks||[]).filter((x:any)=>authMatches(x.auth_version,jwtVersion));
  if(rawLinks?.length&&!links.length)return reply({error:"credential_generation_revoked"},401);
  if(!links.length)return reply({error:"guardian_access_not_found"},403);
  const clientIds=[...new Set(links.map((x:any)=>x.client_id))] as string[],now=new Date(),today=dayKey(now),from=new Date(now.getTime()-180*86400000).toISOString(),until=new Date(now.getTime()+365*86400000).toISOString();
  const [clientsQ,assessmentsQ,goalsQ,programsQ,sessionsQ,behaviorsQ,indicatorsQ,indicatorRecordsQ,appointmentsQ,assignmentsQ]=await Promise.all([
   admin.from("aba_clients").select("id,full_name,preferred_name,birth_date").in("id",clientIds).eq("active",true),
   byClient(clientIds,c=>admin.from("aba_assessments").select("id,client_id,protocol_id,assessment_date,status,reeval_due").eq("client_id",c).neq("status","archived").order("assessment_date",{ascending:false}).limit(200)),
   byClient(clientIds,c=>admin.from("aba_goals").select("id,client_id,title,domain,status,priority,target,review_date,responsible_professional_id").eq("client_id",c).neq("status","closed").order("created_at",{ascending:false}).limit(500)),
   byClient(clientIds,c=>admin.from("aba_programs").select("id,client_id,goal_id,name,domain,status,review_date,objective,operational_definition").eq("client_id",c).neq("status","closed").order("created_at",{ascending:false}).limit(500)),
   byClient(clientIds,c=>admin.from("aba_sessions").select("id,client_id,professional_id,started_at,ended_at,context,modality,status,integrity_pct,ioa_pct").eq("client_id",c).gte("started_at",from).order("started_at",{ascending:false}).limit(300)),
   byClient(clientIds,c=>admin.from("aba_behavior_records").select("id,session_id,client_id,professional_id,occurred_at,topography,antecedent,consequence,hypothesized_function,frequency,duration_seconds,latency_seconds,intensity,context,notes").eq("client_id",c).gte("occurred_at",from).order("occurred_at",{ascending:false}).limit(300)),
   byClient(clientIds,c=>admin.from("aba_indicators").select("id,client_id,name,category,description,measure_type,unit,scale,periodicity,target,review_date").eq("client_id",c).eq("active",true).order("created_at",{ascending:false}).limit(500)),
   byClient(clientIds,c=>admin.from("aba_indicator_records").select("id,indicator_id,client_id,session_id,professional_id,observed_at,value_numeric,value_text,numerator,denominator,frequency_count,duration_seconds,latency_seconds,opportunities,successes,prompt_level,notes").eq("client_id",c).gte("observed_at",from).order("observed_at",{ascending:false}).limit(1000)),
   byClient(clientIds,c=>admin.from("aba_appointments").select("id,client_id,professional_id,specialty,starts_at,ends_at,modality,appointment_type,status,notes").eq("client_id",c).gte("starts_at",from).lte("starts_at",until).order("starts_at",{ascending:true}).limit(500)),
   byClient(clientIds,c=>admin.from("aba_client_professionals").select("client_id,professional_id,assignment_role,starts_on,ends_on").eq("client_id",c).eq("active",true).limit(100))
  ]);
  for(const q of [clientsQ,assessmentsQ,goalsQ,programsQ,sessionsQ,behaviorsQ,indicatorsQ,indicatorRecordsQ,appointmentsQ,assignmentsQ])if(q.error)throw q.error;
  const clients=clientsQ.data||[],assessments=assessmentsQ.data||[],goals=goalsQ.data||[],programs=programsQ.data||[],sessions=sessionsQ.data||[],behaviors=behaviorsQ.data||[],indicators=indicatorsQ.data||[],indicatorRecords=indicatorRecordsQ.data||[],appointments=appointmentsQ.data||[],assignments=assignmentsQ.data||[];
  const protocolIds=[...new Set(assessments.map((x:any)=>x.protocol_id).filter(Boolean))],relatedIds=(rows:any[],cid:string)=>rows.filter(x=>x.client_id===cid).map(x=>x.id),professionalIds=[...new Set([...sessions.map((x:any)=>x.professional_id),...behaviors.map((x:any)=>x.professional_id),...indicatorRecords.map((x:any)=>x.professional_id),...appointments.map((x:any)=>x.professional_id),...assignments.map((x:any)=>x.professional_id),...goals.map((x:any)=>x.responsible_professional_id)].filter(Boolean))];
  const [protocolsQ,resultsQ,summariesQ,targetsQ,trialsQ,professionalsQ]=await Promise.all([
   protocolIds.length?admin.from("aba_protocols").select("id,name").in("id",protocolIds):Promise.resolve({data:[],error:null}),
   byClient(clientIds,c=>{const ids=relatedIds(assessments,c);return ids.length?admin.from("aba_assessment_results").select("assessment_id,domain,result_state,score,score_max").in("assessment_id",ids).limit(5000):Promise.resolve({data:[],error:null})}),
   byClient(clientIds,c=>{const ids=relatedIds(assessments,c);return ids.length?admin.from("aba_assessment_summaries").select("assessment_id,item_count,score,score_max,percent,objective,status,next_reevaluation_label").in("assessment_id",ids).neq("status","archived").limit(500):Promise.resolve({data:[],error:null})}),
   byClient(clientIds,c=>{const ids=relatedIds(programs,c);return ids.length?admin.from("aba_targets").select("id,program_id,name,status,expected_response,mastery_criterion").in("program_id",ids).not("status","in","(closed,paused)").order("position").limit(5000):Promise.resolve({data:[],error:null})}),
   byClient(clientIds,c=>{const ids=relatedIds(sessions,c);return ids.length?admin.from("aba_trials").select("id,session_id,program_id,target_id,result,prompt_type,prompt_intensity,attempted_at").in("session_id",ids).is("voided_at",null).order("attempted_at").limit(5000):Promise.resolve({data:[],error:null})}),
   professionalIds.length?admin.from("aba_professionals").select("id,full_name,specialty,role").in("id",professionalIds).eq("active",true):Promise.resolve({data:[],error:null})
  ]);
  for(const q of [protocolsQ,resultsQ,summariesQ,targetsQ,trialsQ,professionalsQ])if(q.error)throw q.error;
  const protocols=protocolsQ.data||[],results=resultsQ.data||[],summaries=summariesQ.data||[],targets=targetsQ.data||[],trials=trialsQ.data||[],professionals=professionalsQ.data||[],protocolMap=new Map(protocols.map((x:any)=>[x.id,x.name])),professionalMap=new Map(professionals.map((x:any)=>[x.id,x])),summaryMap=new Map(summaries.map((x:any)=>[x.assessment_id,x])),indicatorMap=new Map(indicators.map((x:any)=>[x.id,x]));
  const monitoredClients=clients.map((client:any)=>{
   const access=links.find((x:any)=>x.client_id===client.id),canAssess=!!access?.can_view_assessments,canSessions=!!access?.can_view_sessions,canPrograms=!!access?.can_view_programs,childAssessments=assessments.filter((x:any)=>x.client_id===client.id),childGoals=goals.filter((x:any)=>x.client_id===client.id),childPrograms=programs.filter((x:any)=>x.client_id===client.id),childSessions=sessions.filter((x:any)=>x.client_id===client.id),childBehaviors=behaviors.filter((x:any)=>x.client_id===client.id),childIndicators=indicators.filter((x:any)=>x.client_id===client.id),childIndicatorRecords=indicatorRecords.filter((x:any)=>x.client_id===client.id),childAppointments=appointments.filter((x:any)=>x.client_id===client.id),childAssignments=assignments.filter((x:any)=>x.client_id===client.id),childTrials=trials.filter((t:any)=>childSessions.some((s:any)=>s.id===t.session_id)),childResults=results.filter((r:any)=>childAssessments.some((a:any)=>a.id===r.assessment_id));
   const assessmentSummaries=childAssessments.map((a:any)=>{const rows=childResults.filter((r:any)=>r.assessment_id===a.id),tested=rows.filter((r:any)=>r.result_state==="tested"),consolidated:any=summaryMap.get(a.id),byDomain:Record<string,{tested:number;score:number;max:number}>={};for(const r of tested){const d=r.domain||"Sem domínio";byDomain[d]||={tested:0,score:0,max:0};byDomain[d].tested++;if(r.score!=null)byDomain[d].score+=Number(r.score);if(r.score_max!=null)byDomain[d].max+=Number(r.score_max)}return {id:a.id,date:a.assessment_date,protocol:protocolMap.get(a.protocol_id)||a.protocol_id,status:a.status,reeval_due:a.reeval_due,tested_items:consolidated?.item_count??tested.length,domains:Object.entries(byDomain).map(([domain,v])=>({domain,tested:v.tested,percent:v.max>0?pct(v.score,v.max):null})),score:consolidated?.score??null,score_max:consolidated?.score_max??null,percent:consolidated?.percent??null,objective:consolidated?.objective||null,next_reevaluation_label:consolidated?.next_reevaluation_label||null}});
   const sessionSummaries=childSessions.slice(0,60).map((s:any)=>{const rows=childTrials.filter((t:any)=>t.session_id===s.id),counts={independent:rows.filter((r:any)=>r.result==="independent_correct").length,prompted:rows.filter((r:any)=>r.result==="prompted_correct").length,incorrect:rows.filter((r:any)=>r.result==="incorrect").length,no_response:rows.filter((r:any)=>r.result==="no_response").length,alternative:rows.filter((r:any)=>r.result==="alternative_response").length,interfering:rows.filter((r:any)=>r.result==="interfering_behavior").length},correct=counts.independent+counts.prompted,p:any=professionalMap.get(s.professional_id);return {id:s.id,date:s.started_at,started_at:s.started_at,ended_at:s.ended_at,duration_minutes:durationMinutes(s.started_at,s.ended_at),status:s.status,professional:p?.full_name||null,modality:s.modality,context:s.context,trials:rows.length,independence:pct(counts.independent,rows.length),accuracy:pct(correct,rows.length),interfering_pct:pct(counts.interfering,rows.length),integrity_pct:asNumber(s.integrity_pct),ioa_pct:asNumber(s.ioa_pct),counts}});
   const programSummaries=childPrograms.map((p:any)=>{const rows=childTrials.filter((t:any)=>t.program_id===p.id),ind=rows.filter((r:any)=>r.result==="independent_correct").length,correct=rows.filter((r:any)=>["independent_correct","prompted_correct"].includes(r.result)).length,inter=rows.filter((r:any)=>r.result==="interfering_behavior").length;return {id:p.id,goal_id:p.goal_id,name:p.name,domain:p.domain,status:p.status,objective:p.objective,operational_definition:p.operational_definition,review_date:p.review_date,trials:rows.length,independence:pct(ind,rows.length),accuracy:pct(correct,rows.length),interfering_pct:pct(inter,rows.length),targets:targets.filter((t:any)=>t.program_id===p.id).map((t:any)=>({id:t.id,name:t.name,status:t.status,expected_response:t.expected_response,mastery_criterion:t.mastery_criterion}))}});
   const behaviorSummaries=childBehaviors.map((r:any)=>({...r,professional:(professionalMap.get(r.professional_id) as any)?.full_name||null,measure_summary:behaviorMeasure(r)}));
   const indicatorSummaries=childIndicators.map((i:any)=>{const records=childIndicatorRecords.filter((r:any)=>r.indicator_id===i.id).slice(0,30).map((r:any)=>({...r,professional:(professionalMap.get(r.professional_id) as any)?.full_name||null,display:indicatorValue(i,r)}));return {...i,records,latest:records[0]||null}});
   const appointmentSummaries=childAppointments.map((a:any)=>({...a,professional:(professionalMap.get(a.professional_id) as any)?.full_name||null})),upcoming=appointmentSummaries.filter((a:any)=>new Date(a.starts_at)>=now&&a.status!=="cancelled"),team=childAssignments.map((a:any)=>{const p:any=professionalMap.get(a.professional_id);return {id:a.professional_id,name:p?.full_name||"Profissional",specialty:p?.specialty||null,role:p?.role||null,assignment_role:a.assignment_role,starts_on:a.starts_on,ends_on:a.ends_on}});
   const activity=[...(canSessions?sessionSummaries.filter((x:any)=>new Date(x.started_at)<=now).map((x:any)=>({type:"session",at:x.started_at,title:`Sessão ${x.status==="open"?"em andamento":"registrada"}`,summary:`${x.professional||"Profissional"} · ${x.trials} tentativa(s) · ${x.independence}% independente`})):[]),...(canSessions?behaviorSummaries.map((x:any)=>({type:"behavior",at:x.occurred_at,title:x.topography,summary:`${x.measure_summary}${x.professional?` · ${x.professional}`:""}`})):[]),...(canSessions?childIndicatorRecords.map((x:any)=>{const i:any=indicatorMap.get(x.indicator_id),d=indicatorValue(i,x);return {type:"indicator",at:x.observed_at,title:i?.name||"Indicador registrado",summary:d?`${d.value}${d.unit?` ${d.unit}`:""}${d.detail?` (${d.detail})`:""}`:"medida registrada"}}):[]),...(canAssess?assessmentSummaries.map((x:any)=>({type:"assessment",at:`${x.date}T12:00:00-03:00`,title:`Avaliação · ${x.protocol}`,summary:`${x.tested_items} item(ns) avaliados`})):[])].sort((a:any,b:any)=>new Date(b.at).getTime()-new Date(a.at).getTime()).slice(0,100);
   const futureReevaluation=canAssess?assessmentSummaries.map((x:any)=>x.next_reevaluation_label||x.reeval_due).filter(Boolean)[0]||null:null,futureReview=canPrograms?childPrograms.map((x:any)=>x.review_date).filter(Boolean).sort()[0]||null:null,updatesToday=activity.filter((x:any)=>dayKey(x.at)===today).length,trialsToday=childTrials.filter((x:any)=>dayKey(x.attempted_at)===today).length,interferingToday=childTrials.filter((x:any)=>dayKey(x.attempted_at)===today&&x.result==="interfering_behavior").length;
   return {id:client.id,name:client.preferred_name||client.full_name,full_name:client.full_name,birth_date:client.birth_date,relationship:access?.relationship||"responsável",permissions:{assessments:canAssess,sessions:canSessions,programs:canPrograms},cards:{last_assessment:canAssess?assessmentSummaries[0]||null:null,next_reevaluation:futureReevaluation||futureReview,sessions_completed:canSessions?childSessions.filter((x:any)=>x.status==="completed").length:null,active_programs:canPrograms?childPrograms.filter((x:any)=>!["paused","closed","reserve"].includes(x.status)).length:null,updates_today:updatesToday,trials_today:canSessions?trialsToday:null,interfering_today:canSessions?interferingToday:null,behaviors_30d:canSessions?childBehaviors.filter((x:any)=>new Date(x.occurred_at)>=new Date(now.getTime()-30*86400000)).length:null,next_appointment:canSessions?upcoming[0]||null:null,latest_activity:activity[0]||null},assessments:canAssess?assessmentSummaries:[],goals:canPrograms?childGoals.map((g:any)=>({...g,responsible:(professionalMap.get(g.responsible_professional_id) as any)?.full_name||null})):[],programs:canPrograms?programSummaries:[],sessions:canSessions?sessionSummaries:[],behaviors:canSessions?behaviorSummaries:[],indicators:canSessions?indicatorSummaries:[],appointments:canSessions?appointmentSummaries:[],team:canSessions?team:[],activity};
  });
  return reply({ok:true,guardian_name:links[0]?.guardian_name||null,guardian_email:user.email||links[0]?.guardian_email||null,clients:monitoredClients,children:monitoredClients,generated_at:new Date().toISOString(),refresh_after_seconds:60});
 }catch(error){console.error("aba_parent_dashboard_error",error);return reply({error:String((error as any)?.message||error)},500)}
});
